# Generated by Django 5.1.7 on 2025-04-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiere', '0002_alter_filiere_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('filieres', models.ManyToManyField(related_name='classes', to='filiere.filiere')),
            ],
        ),
    ]
