# Generated by Django 5.1.7 on 2025-04-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='filieres',
        ),
    ]
