# Generated by Django 4.2.16 on 2025-08-16 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pointage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pointage',
            unique_together={('session', 'user')},
        ),
    ]
