# Generated by Django 4.2.16 on 2025-08-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start_course', models.TimeField()),
                ('time_end_course', models.TimeField()),
                ('jours', models.CharField(max_length=8)),
                ('salle', models.CharField(max_length=50, null=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horaires', to='module.module')),
            ],
        ),
    ]
