# Generated by Django 4.2.16 on 2025-08-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('is_validated_by_professor', models.BooleanField(default=False)),
                ('is_validated_by_admin', models.BooleanField(default=False)),
                ('horaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plannings', to='horaire.horaire')),
            ],
        ),
    ]
