# Generated by Django 5.1.7 on 2025-04-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='his_state',
            field=models.BooleanField(default=False),
        ),
    ]
