# Generated by Django 5.1.7 on 2025-05-16 08:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horaire', '0001_initial'),
        ('planning', '0002_planning_his_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='salle',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='time_end_course',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='time_start_course',
        ),
        migrations.AddField(
            model_name='planning',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='planning',
            name='horaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning', to='horaire.horaire'),
        ),
    ]
