# Generated by Django 5.1.7 on 2025-05-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_remove_planning_salle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
