# Generated by Django 5.1.7 on 2025-05-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_alter_planning_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='validate',
            field=models.BooleanField(default=False),
        ),
    ]
