# Generated by Django 5.1.7 on 2025-05-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_alter_planning_validate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='his_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='validate',
            field=models.BooleanField(default=False),
        ),
    ]
