# Generated by Django 4.2.16 on 2025-08-15 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('horaire', '0001_initial'),
        ('planning', '0008_alter_planning_his_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planning',
            old_name='his_state',
            new_name='is_validated_by_admin',
        ),
        migrations.RenameField(
            model_name='planning',
            old_name='validate',
            new_name='is_validated_by_professor',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='module',
        ),
        migrations.AlterField(
            model_name='planning',
            name='horaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plannings', to='horaire.horaire'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plannings', to=settings.AUTH_USER_MODEL),
        ),
    ]
