# Generated by Django 5.1.7 on 2025-04-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='modules',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='module.module'),
        ),
    ]
