# Generated by Django 4.2.16 on 2025-09-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_roles_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fonction',
        ),
    ]
