# Generated by Django 4.2.12 on 2025-07-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('users', '0005_remove_user_photo_url_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='role.role'),
        ),
    ]
