# Generated by Django 4.2.12 on 2025-07-04 17:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('users', '0006_alter_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_encoding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='role.role'),
        ),
    ]
