# Generated by Django 4.2.12 on 2025-07-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_face_encoding_alter_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='face_encoding',
        ),
    ]
