# Generated by Django 5.1.7 on 2025-03-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiere', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
