# Generated by Django 4.2.16 on 2025-08-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('NON_JUSTIFIEE', 'Non justifiée'), ('EN_ATTENTE', 'En attente de validation'), ('APPROUVEE', 'Approuvée'), ('REFUSEE', 'Refusée')], default='NON_JUSTIFIEE', max_length=20)),
                ('justificatif_texte', models.TextField(blank=True, help_text="Texte de justification soumis par l'étudiant.", null=True)),
                ('justificatif_document', models.FileField(blank=True, help_text="Document (PDF, image) soumis par l'étudiant.", null=True, upload_to='justificatifs_absences/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
