# Generated by Django 4.2.16 on 2025-08-11 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0008_alter_planning_his_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('NON_JUSTIFIEE', 'Non justifiée'), ('EN_ATTENTE', 'En attente de validation'), ('APPROUVEE', 'Approuvée'), ('REFUSEE', 'Refusée')], default='NON_JUSTIFIEE', max_length=20)),
                ('justificatif_texte', models.TextField(blank=True, help_text="Texte de justification soumis par l'étudiant.", null=True)),
                ('justificatif_document', models.FileField(blank=True, help_text="Document (PDF, image) soumis par l'étudiant.", null=True, upload_to='justificatifs_absences/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='planning.planning')),
                ('user', models.ForeignKey(limit_choices_to={'roles__name': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
                'unique_together': {('user', 'planning')},
            },
        ),
    ]
