# Generated by Django 4.2.16 on 2025-08-16 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('absences', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='user',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('user', 'planning')},
        ),
    ]
