# Generated by Django 4.2.16 on 2025-08-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classe', '0001_initial'),
        ('filiere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('session', models.TextField(blank=True, max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='classe.classe')),
                ('filieres', models.ManyToManyField(blank=True, related_name='modules', to='filiere.filiere')),
            ],
        ),
    ]
