# Generated by Django 5.1.7 on 2025-04-09 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classe', '0001_initial'),
        ('filiere', '0002_alter_filiere_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('session', models.TextField(blank=True, max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='classe.classe')),
                ('filieres', models.ManyToManyField(related_name='modules', to='filiere.filiere')),
            ],
        ),
    ]
