# Generated by Django 5.1.7 on 2025-04-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiere', '0002_alter_filiere_name'),
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='filieres',
            field=models.ManyToManyField(blank=True, related_name='modules', to='filiere.filiere'),
        ),
    ]
